-- BigQuery view definitions for unified alert access

CREATE OR REPLACE VIEW `viewpers.salesguard_alerts.alerts_v2_compat_unified` AS
SELECT
  alert_id AS id,
  message_id,
  thread_id,
  thread_id_norm,
  in_reply_to,
  reply_level,
  is_root,
  datetime,
  DATE(datetime) AS event_date,
  status,
  level,
  keyword,
  department,
  assigned_user_id,
  assignee_name,
  score,
  detection_score,
  composite_risk,
  sentiment_label,
  sentiment_score,
  negative_flag,
  primary_risk_type,
  risk_keywords,
  company_domain,
  company_domain_norm,
  customer_email,
  customer_email_norm,
  person,
  person_norm,
  customer_name_header,
  customer_display_name,
  company_name,
  direction,
  subject,
  subject_norm,
  description,
  message_body,
  body_preview,
  body_snippet,
  source_uri,
  source_file,
  seg_lose,
  seg_rival,
  seg_addreq,
  seg_renewal
FROM `viewpers.salesguard_alerts.unified_email_messages`;

CREATE OR REPLACE VIEW `viewpers.salesguard_alerts.messages_compat_unified` AS
SELECT
  message_id,
  thread_id,
  thread_id_norm,
  datetime,
  subject,
  subject_norm,
  message_body,
  body_preview,
  body_snippet,
  source_uri,
  source_file,
  person,
  person_norm,
  customer_email,
  customer_email_norm,
  customer_name_header,
  company_domain,
  company_domain_norm
FROM `viewpers.salesguard_alerts.unified_email_messages`;
