-- Seed dummy data for dataset viewpers.salesguard_alerts_dummy

CREATE OR REPLACE TABLE `viewpers.salesguard_alerts_dummy.unified_email_messages` AS
SELECT
  'msg-001' AS message_id,
  'thread-001' AS thread_id,
  NULL AS in_reply_to,
  0 AS reply_level,
  TRUE AS is_root,
  TIMESTAMP '2025-07-10 00:00:00' AS datetime,
  'customer@example.com' AS `from`,
  'sales@company.jp' AS `to`,
  '契約更新のご相談' AS subject,
  '更新に関するご相談です。' AS body_preview,
  'gs://dummy/source/001' AS source_uri,
  'clientcorp.jp' AS company_domain,
  'inbound' AS direction,
  'renewal' AS primary_risk_type,
  '更新,相談' AS risk_keywords,
  55 AS score,
  'negative' AS sentiment_label,
  -0.4 AS sentiment_score,
  TRUE AS negative_flag,
  'manager@company.jp' AS cc_emails,
  NULL AS bcc_emails,
  '契約' AS segment_category,
  'high' AS priority_level,
  'フォロー推奨' AS recommended_action,
  '24h' AS estimated_response_time,
  '契約更新' AS primary_segment,
  0.85 AS segment_confidence
UNION ALL SELECT
  'msg-002',
  'thread-001',
  'msg-001',
  1,
  FALSE,
  TIMESTAMP '2025-07-10 03:00:00',
  'sales@company.jp',
  'customer@example.com',
  'Re: 契約更新のご相談',
  'ご相談ありがとうございます。詳細をご連絡します。',
  'gs://dummy/source/002',
  'company.jp',
  'outbound',
  'info',
  'お礼,確認',
  70,
  'positive',
  0.3,
  FALSE,
  NULL,
  NULL,
  '契約',
  'high',
  '詳細案内を送付',
  '6h',
  '契約更新',
  0.9
UNION ALL SELECT
  'msg-003',
  'thread-001',
  'msg-002',
  2,
  FALSE,
  TIMESTAMP '2025-07-11 02:00:00',
  'customer@example.com',
  'sales@company.jp',
  'Re: 契約更新のご相談',
  'ご返信ありがとうございます。最終確認です。',
  'gs://dummy/source/003',
  'clientcorp.jp',
  'inbound',
  'renewal',
  '確認',
  60,
  'neutral',
  -0.1,
  TRUE,
  NULL,
  NULL,
  '契約',
  'medium',
  '対応状況確認',
  '12h',
  '契約更新',
  0.8
UNION ALL SELECT
  'msg-004',
  'thread-002',
  NULL,
  0,
  TRUE,
  TIMESTAMP '2025-07-09 10:00:00',
  'vip_client@example.com',
  'support@company.jp',
  '導入後の不具合について',
  '導入後に不具合が発生しています。',
  'gs://dummy/source/004',
  'vipco.jp',
  'inbound',
  'complaint',
  '不具合,至急',
  80,
  'negative',
  -0.6,
  TRUE,
  'lead@company.jp',
  NULL,
  'クレーム',
  'high',
  '至急対応',
  '4h',
  'サポート',
  0.92
UNION ALL SELECT
  'msg-005',
  'thread-002',
  'msg-004',
  1,
  FALSE,
  TIMESTAMP '2025-07-09 11:30:00',
  'support@company.jp',
  'vip_client@example.com',
  'Re: 導入後の不具合について',
  '不具合の詳細を教えてください。',
  'gs://dummy/source/005',
  'company.jp',
  'outbound',
  'support',
  '確認',
  65,
  'neutral',
  0.1,
  FALSE,
  NULL,
  NULL,
  'クレーム',
  'high',
  '詳細ヒアリング',
  '6h',
  'サポート',
  0.75
UNION ALL SELECT
  'msg-006',
  'thread-002',
  'msg-005',
  2,
  FALSE,
  TIMESTAMP '2025-07-09 13:00:00',
  'vip_client@example.com',
  'support@company.jp',
  'Re: 導入後の不具合について',
  '添付資料をご確認ください。',
  'gs://dummy/source/006',
  'vipco.jp',
  'inbound',
  'complaint',
  '添付',
  75,
  'negative',
  -0.5,
  TRUE,
  NULL,
  NULL,
  'クレーム',
  'high',
  '対応中',
  '6h',
  'サポート',
  0.88;

CREATE OR REPLACE TABLE `viewpers.salesguard_alerts_dummy.alerts_v2_scored` AS
SELECT
  'alert-001' AS id,
  'ALT-001' AS original_alert_id,
  'msg-001' AS message_id,
  'pending' AS status,
  'high' AS level,
  85 AS score,
  '契約更新' AS keyword,
  '営業部' AS department,
  'user-001' AS assigned_user_id,
  'customer@example.com' AS customer_email,
  TIMESTAMP '2025-07-10 00:05:00' AS datetime,
  TIMESTAMP '2025-07-10 01:00:00' AS updated_at,
  CAST(NULL AS TIMESTAMP) AS resolved_at,
  CAST(NULL AS STRING) AS resolved_by,
  CAST(NULL AS STRING) AS resolution_note,
  'sales@company.jp' AS person,
  '契約更新に関するご相談です。' AS description,
  'ご相談ありがとうございます。詳細をご連絡します。' AS messageBody,
  'gs://dummy/source/alert001' AS source_file,
  'thread-001' AS thread_id,
  1 AS reply_level,
  FALSE AS is_root
UNION ALL SELECT
  'alert-002',
  'ALT-002',
  'msg-004',
  'in_progress',
  'high',
  92,
  '不具合',
  'サポート',
  'user-002',
  'vip_client@example.com',
  TIMESTAMP '2025-07-09 10:05:00',
  TIMESTAMP '2025-07-09 14:00:00',
  CAST(NULL AS TIMESTAMP),
  CAST(NULL AS STRING),
  CAST(NULL AS STRING),
  'support@company.jp',
  '導入後の不具合について',
  '詳細を確認中です。',
  'gs://dummy/source/alert002',
  'thread-002',
  1,
  FALSE;
