import { DetectionRuleDescriptor } from './models';
import { SEGMENT_META } from '@/lib/segments';

const jp = (...words: string[]) => words;

export const DETECTION_RULES: DetectionRuleDescriptor[] = [
  {
    key: 'forecast_trust_risk',
    segment: 'forecast',
    keywords: jp('ROI', '不安', '懸念', '比較', '競合', '稟議'),
    maxSentiment: -0.05,
    severity: 'B',
    urgency: 60,
    description: 'ROI や進め方への不安が顕在化しているケース',
  },
  {
    key: 'forecast_response_quality',
    segment: 'forecast',
    keywords: jp('夜間', '品質', 'ばらつき', '即時対応', '遅延'),
    minSentiment: -0.4,
    severity: 'B',
    urgency: 55,
    description: '夜間対応や回答品質に関する懸念を検知',
  },
  {
    key: 'forecast_tone_down',
    segment: 'forecast',
    keywords: jp('トーン', '熱量', '反応が薄い', '検討中'),
    maxSentiment: 0.15,
    severity: 'C',
    urgency: 45,
    description: SEGMENT_META.forecast.detectionLabel,
  },
  {
    key: 'forecast_inactive',
    segment: 'forecast',
    direction: 'outbound',
    minHoursSinceLastReply: 48,
    severity: 'B',
    urgency: 52,
    description: 'こちらの連絡後に返信が途絶えているケース',
  },
  {
    key: 'occurrence_complaint',
    segment: 'occurrence',
    keywords: jp('不満', 'クレーム', 'トラブル', '不具合', 'エラー', '高すぎる'),
    maxSentiment: -0.2,
    severity: 'A',
    urgency: 85,
    description: '顧客から機能・価格・対応面の不満が届いている',
  },
  {
    key: 'occurrence_silence',
    segment: 'occurrence',
    direction: 'outbound',
    minHoursSinceLastReply: 72,
    severity: 'B',
    urgency: 70,
    description: 'こちらの接触後に顧客側で沈黙が続くケース',
  },
  {
    key: 'occurrence_proposal_issue',
    segment: 'occurrence',
    keywords: jp('修正', '変更', '違う', '期待', '要望', '資料', '再共有', '認識齟齬'),
    severity: 'B',
    urgency: 68,
    description: '提案内容に対する齟齬・修正依頼を検知',
  },
  {
    key: 'occurrence_reoccurrence',
    segment: 'occurrence',
    keywords: jp('再発', '同じ問題', 'また', '再度', '繰り返し'),
    severity: 'A',
    urgency: 80,
    description: '過去に解決済みの課題が再燃している',
  },
  {
    key: 'occurrence_followup',
    segment: 'occurrence',
    keywords: jp('フォロー', '至急', '回答希望', '決裁'),
    direction: 'inbound',
    maxSentiment: 0.05,
    severity: 'B',
    urgency: 72,
    description: SEGMENT_META.occurrence?.detectionLabel ?? 'フォローアップが必要なケース',
  },
  {
    key: 'follow_recovery',
    segment: 'follow',
    keywords: jp('改善', '再開', 'レビュー', 'サクセス', '状況確認'),
    minSentiment: 0,
    severity: 'C',
    urgency: 40,
    description: '施策後の改善状況、ポジティブなフォロー依頼',
  },
];
